name: deeplearn_env
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy=1.23.5
  - scipy=1.8.1
  - pandas
  - scikit-learn
  - rdkit=2023.03.1
  - joblib
  - pillow
  - h5py
  - matplotlib
  - seaborn
  - tqdm
  - pytorch
  - cpuonly
  - pip:
      - deepchem==2.7.1
      - tensorflow==2.12.0
      - jax==0.4.13
      - jaxlib==0.4.13
      - dm-haiku
      - optax
      - torch_geometric
      - pytorch-lightning
